services:
  app:
    image: ghcr.io/lilkidsuave/ente-simple-docker:latest
    container_name: ente
    environment:
      NEXT_PUBLIC_ENTE_ENDPOINT: "https://foo.bar"
      NEXT_PUBLIC_ALBUMS_ENDPOINT: "https://foo.bar"
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
    restart: always
